version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: practica_api_docker
    environment:
      POSTGRES_USER: daysuke
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:

